### ISSUE TITLE
commitMessagePrefix does not work

### ISSUE THREAD

**Issue by dword-design** [Jaid/action-sync-node-meta#13]
Hey, I really like this action and hope to have it integrated in my workflow soon!

Unfortunately the `commitMessagePrefix` variable is not working. None of the commit messages gets the prefix. I briefly looked into the source code and it looks like the uses of `commit-in-action` does not fit to the actual library signature. E.g. the `CommitManager.push` method does not take any arguments, but the prefixed commit message is passed to this function.

I rely on semantic commits, so that's an issue :P.

Check the commit messages and GitHub workflow config here:
https://github.com/dword-design/test-sync-github-metadata/commits/master

**Comment by dword-design** [comment]
@Jaid I added a PR that should fix the issue https://github.com/Jaid/action-sync-node-meta/pull/14.

**Comment by Jaid** [comment]
I removed input “commitMessagePrefix” in favor of new input “commitMessage”. This is more flexible and makes it clear where spaces are used in the final commit message.

Old input:
```yaml
  commitMessagePrefix:
    description: Prefix string used in messages for automatically generated commits
    default: "autofix: "
    required: false
```

New input:
```yaml
  commitMessage:
    description: Commit message for package.json changes (only for direction "overwrite-file"). Substring “{changes}” will be replaced with a list of changed package.json fields.
    default: "autofix: Updated package.json[{changes}]"
    required: false
```

Commit:

- [Removed input “commitMessagePrefix” in favor of new input “commitMessage”](https://github.com/Jaid/action-sync-node-meta/commit/abe5d6e96d6d69983bfab317bd185d94238c0627)
